### ISSUE TITLE
Import translation data as new spheres does not work properly with certain column header names

### ISSUE THREAD

**Issue by M-Mielke** [pfalkingham/XROMM_BlenderTools#1]
I have a csv file with 3D data of markers exported from XMALab that I try to import in Blender via "Import Translations/Rotations" as new spheres.
My columns are named like this:

head_front_60Hz_X, head_front_60Hz_Y, head_front_60Hz_Z, 
head_back_60Hz_X, head_back_60Hz_Y, head_back_60Hz_Z,
[...]
maxilla_leftfront_60Hz_X, maxilla_leftfront_60Hz_Y, maxilla_leftfront_60Hz_Z,
maxilla_leftback_60Hz_X, maxilla_leftback_60Hz_Y, maxilla_leftback_60Hz_Z,
[...]
etc.

When I import this csv file, only one marker per rigid body is imported to the correct position, named "head", "maxilla", etc. All other markers (I have 4 in total per RB) are placed at (0,0,0).

Import works as expected, however, when I first rename my columns to this (avoiding the firs underscore):

headfront_60Hz_X, headfront_60Hz_Y, headfront_60Hz_Z, 
headback_60Hz_X, headback_60Hz_Y, headback_60Hz_Z,
[...]
maxillaleftfront_60Hz_X, maxillaleftfront_60Hz_Y, maxillaleftfront_60Hz_Z,
maxillaleftback_60Hz_X, maxillaleftback_60Hz_Y, maxillaleftback_60Hz_Z,
[...]
etc.

Then the data is imported properly and spheres are named "headfront", "headback", "maxillaleftfront", "maxillaleftback", as expected.

Here are two csv files attached, one that is not working (with my original column names) and one that is working (with renamed columns).

[3Ddata_notWorking.csv](https://github.com/pfalkingham/XROMM_BlenderTools/files/12496258/3Ddata_notWorking.csv)
[3Ddata_working.csv](https://github.com/pfalkingham/XROMM_BlenderTools/files/12496259/3Ddata_working.csv)

**Comment by pfalkingham** [comment]
This is fixed in v0.91 - I changed the way it was handling the underscores - previously it was keeping everything before the first underscore, with this:

name = header[i].split('_')[0]

But that's now changed to 

name = header[i].rsplit('_',1)[0]

Which keeps everything before the _last_ underscore.  Tested with your files (thanks!) and it seems to work.
